Add PostgreSQL database backend for naffka
matrix-org/naffka pull request #3
Opened 2017-08-11 16:57 UTC by NegativeMjark

2017-08-14 13:56 UTC, richvdh requested changes

2017-08-14 13:56 UTC, richvdh commented on postgresqldatabase.go
> +	topic_name TEXT PRIMARY KEY,
shouldn't the `nid` be the primary key?

2017-08-14 13:56 UTC, richvdh commented on postgresqldatabase.go
> +		return p.getTopicNID(txn, topicName)
I'm a bit confused about why both this and `ON CONFLICT DO NOTHING RETURNING (topic_nid)` are necessary. Cn you explain?

2017-08-14 13:56 UTC, richvdh commented on postgresqldatabase.go
> +	rows, err := p.selectMaxOffsetStmt.Query(topicNID, startOffset, endOffset)
selectMessagesStmt ?

2017-08-15 10:44 UTC, NegativeMjark commented on postgresqldatabase.go
> +	topic_name TEXT PRIMARY KEY,
This is a table to lookup topic_name to topic_nid, we don't actually need to go the other way.

2017-08-15 10:44 UTC, NegativeMjark commented on postgresqldatabase.go
> +	rows, err := p.selectMaxOffsetStmt.Query(topicNID, startOffset, endOffset)
oops, fixed in 671be41

2017-08-15 10:47 UTC, NegativeMjark commented on postgresqldatabase.go
> +		return p.getTopicNID(txn, topicName)
Yep, I've explained in 671be41 and 6612b90

2017-08-15 14:16 UTC, richvdh commented on postgresqldatabase.go
> +	" ON CONFLICT DO NOTHING RETURNING (topic_nid)"
ohhhh, this isn't `ON CONFLICT (DO NOTHING RETURNING (topic_nid))`, but rather `(ON CONFLICT DO NOTHING) (RETURNING (topic_nid))`.

I think breaking this into two lines would have been less likely to confuse me.

2017-08-15 14:17 UTC, richvdh approved these changes
lgtm, especially if you add a linebreak in `insertTopicSQL`

2017-08-15 15:15 UTC, merged